#Antes de executar o docker-compose.yml. Sempre faça o build da applicação pelo mvn e o build de uma nova imagem docker.
# Primeiro faça:
# mvn clean package
#
#Depois faça:
# docker-compose build
#
#Finalmente, faça:
# docker-compose up
#
version: '3'

services:
  simiantester:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hromenique/simiantester:latest
    container_name: simiantester
    ports:
      - 8080:8080
      - 80:8080
    environment: 
      - PROFILE=docker
    networks:
      - "local-network"
    depends_on: 
      - mongodb
      - redis
  
  mongodb:
    image: mongo
    container_name: mongodb_simiantester
    ports: 
      - 27017:27017
    networks:
      - "local-network"
    volumes:
      - /var/www/volumes/mongo:/data/db

  redis:
    image: redis
    container_name: redis_simiantester
    ports:
      - 6379:6379
    networks:
      - "local-network"

networks:
 local-network:
   driver: bridge




